security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_employee_provider:
            entity:
                class: App\Entity\Employee
                property: username
        app_client_provider:
            entity:
                class: App\Entity\Client
                property: email
        app_all_users_provider:
            chain:
                providers: [app_employee_provider, app_client_provider]

    firewalls:
        dev:
            # Ensure dev tools and static assets are always allowed
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        admin:
            pattern: ^/admin
            lazy: true
            provider: app_employee_provider
            custom_authenticator: App\Security\LoginFormAuthenticator
            logout:
                path: /admin/logout
                target: /admin/login
        employee_login:
            pattern: ^/api/auth/employee
            stateless: true
            provider: app_employee_provider
            user_checker: App\Security\UserChecker
            json_login:
                check_path: /api/auth/employee
                username_path: username
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        client_login:
            pattern: ^/api/auth/client
            stateless: true
            provider: app_client_provider
            user_checker: App\Security\UserChecker
            json_login:
                check_path: /api/auth/client
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern: ^/api
            stateless: true
            provider: app_all_users_provider
            entry_point: jwt
            # json_login:
            #     check_path: /api/auth
            #     username_path: email
            #     password_path: password
            #     success_handler: lexik_jwt_authentication.handler.authentication_success
            #     failure_handler: lexik_jwt_authentication.handler.authentication_failure
            jwt: ~

            # Activate different ways to authenticate:
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    role_hierarchy:
        ROLE_SYS_ADMIN: [ROLE_ADMIN, ROLE_CONTROL, ROLE_CHECKOUT, ROLE_CHECKOUT_MANAGER]
        ROLE_ADMIN: [ROLE_STOCK]
        # employees and clients are users
        ROLE_EMPLOYEE: [ROLE_USER]
        ROLE_CLIENT: [ROLE_USER]

    # Note: Only the *first* matching rule is applied
    access_control:
        # backoffice authentication
        - { path: ^/admin/login$, roles: PUBLIC_ACCESS }
        - { path: ^/admin/logout$, roles: PUBLIC_ACCESS }
        # backoffice access
        - { path: ^/admin, roles: ROLE_STOCK }
         # Swagger documentation
        - { path: ^/api$, roles: PUBLIC_ACCESS }
        # clients API registration
        - { path: ^/api/clients$, methods: [POST], roles: PUBLIC_ACCESS }
        # clients API login
        - { path: ^/api/login$, methods: [POST], roles: PUBLIC_ACCESS }
        - { path: ^/api/clients, roles: ROLE_CLIENT }
        - { path: ^/api/products, roles: PUBLIC_ACCESS }
        # close all API route that are undefined
        - { path: '^/api', roles: ROLE_IMPOSSIBLE }

when@test:
    security:
        password_hashers:
            # Password hashers are resource-intensive by design to ensure security.
            # In tests, it's safe to reduce their cost to improve performance.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
